services:
  marzneshin:
    image: dawsh/marzneshin:latest
    restart: always
    env_file: .env
    network_mode: host
    volumes:
      - /var/lib/marzneshin:/var/lib/marzneshin
    depends_on:
      - db
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 12341234
      MYSQL_DATABASE: marzneshin
    ports:
      - "127.0.0.1:3306:3306"
    volumes:
      - /var/lib/marzneshin/mysql:/var/lib/mysql
