services:
  marzneshin:
    image: dawsh/marzneshin:latest
    restart: always
    env_file: .env
    network_mode: host
    volumes:
      - /var/lib/marzneshin:/var/lib/marzneshin
    depends_on:
      - mariadb
  mariadb:
    image: mariadb:latest
    restart: always
    env_file: .env
    network_mode: host
    environment:
      MYSQL_DATABASE: marzneshin
    volumes:
      - /var/lib/marzneshin/mysql:/var/lib/mysql
